# Travis CI Configuration File
#
# Setting up w/ NodeJS: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

language: node_js
node_js:
  - '8.10.0'
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - 'yarn build:tests'
script:
  - 'ava --verbose --color --watch=false'
git:
  depth: 5
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
