name: Run Tests
on:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-20.04
    container:
      image: python:2.7.18-buster

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: "[Setup] Install dependencies"
        run: yarn
      - name: "[Test] Run linters"
        continue-on-error: true
        run: yarn lint
      - name: "[Test] Run all legacy ava tests"
        run: yarn test:CI
      - name: "[Test] Run all jest tests"
        run: yarn jest
