name: Run Tests
on:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: "[Setup] Install dependencies"
        run: yarn
      - name: "[Test] Run linters"
        run: yarn lint
      - name: "[Test] Run all jest tests"
        run: yarn test
